export const countries: string[] = [
  "Germany",
  "Australia",
  "Austria",
  "Belgium",
  "Bulgaria",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Finland",
  "France",
  "Gibraltar",
  "Great Britain",
  "Greece",
  "Hungary",
  "Ireland",
  "Italy",
  "Liechtenstein",
  "Luxembourg",
  "Netherlands",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
  "Switzerland",
  "United Arab Emirates",
  "USA",
];

export const assetClassOptions: string[] = [
  "Grundstück - Plot",
  "Mehrfamilienhaus - Multi Family House",
  "Wohn- und Geschäftshaus - Residential & Commercial",
  "Wohnung - Condominium",
  "Soziales Wohnen",
  "Büro - Office",
  "Handel - Retail",
  "Logistik - Logistics",
  "Gewerbe - Industry",
  "Gesundheit - Health",
  "Hotel",
  "Micro Living",
  "Senior Living",
  "LifeScience",
  "Mixed Use",
];

export const objectStatusOptions: string[] = [
  "Plot",
  "Project development",
  "Built",
  "Built + Project development",
  "Demolition + Project development",
];

export const energyClassOptions: string[] = [
  "A+",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
];
